package net.peacefulcraft.sco.swordskills;

public enum SwordSkillType
{
	PLAYER_INTERACT, ENTITY_DAMAGE_ENTITY_RECIEVE, ENTITY_DAMAGE_ENTITY_GIVE, 
	PLAYER_DEATH, PLAYER_INTERACT_ENTITY, PLAYER_MOVE, PLAYER_TOGGLE_FLIGHT, 
	PASSIVE
}
