package net.peacefulcraft.sco.swordskills;

public enum SwordSkillType
{
	PLAYER_INTERACT_LEFT_CLICK, PLAYER_INTERACT_RIGHT_CLICK, PLAYER_INTERACT,
	PLAYER_SEND_CHAT, PLAYER_DEATH, PLAYER_INTERACT_ENTITY, PLAYER_MOVE, PLAYER_RESPAWN, 
	ENTITY_DAMAGE_ENTITY_RECIEVE, ENTITY_DAMAGE_ENTITY_GIVE, ENTITY_TELEPORT,
	PASSIVE
}
