name: SwordCraftOnline
main: net.peacefulcraft.sco.SwordCraftOnline
version: 1.0
api-version: 1.14

commands:
    setWaystone:
      description: Set waystone teleports.
      usage: /<command> To set waystone
    setTeleport:
      description: Set teleports.
      usage/<command> To set teleport