debug: false
database:
  ip:
  name:
  user:
  secret:
waystones:
  1: {}
  2: {}
  3: {}
teleport:
  spawn: {}
  quit: {}
dungeon:
  1:
    entrance: {}
    arena: {}
parties: {}
healthbar: "BAR"
spawners: {}