name: SwordCraftOnline
main: net.peacefulcraft.sco.SwordCraftOnline
version: 1.0
api-version: 1.15

commands:
    scoadmin:
      description: Admin Resources
      usage: "/<command> [ swordskillbook | generateitem | playerdata | setplayerdata ]"
    setWaystone:
      description: Set waystone teleports.
      usage: "/<command> [ 1 | 2 | 3 ]"
    setTeleport:
      description: Set teleports.
      usage: "/<command> [ spawn | quit ]"
    party:
      description: all party commands.
      usage: "/<command> [ create | rename | invite | disband | cancelinvite | accept | deny | setleader | leave | name ]"